version: "3.7"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: akshay
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: first-db
    ports:
      - "5433:5432"
    networks:
      - my-network
    volumes:
      - student-data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  student-data:
